# Generated by Django 3.2.9 on 2021-11-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('game_name', models.CharField(max_length=100)),
                ('game_type', models.CharField(max_length=100)),
                ('age_rest', models.IntegerField()),
                ('height_rest', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('duration', models.IntegerField()),
            ],
            options={
                'db_table': 'game',
            },
        ),
    ]
