# Generated by Django 3.2.9 on 2021-11-21 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameZoneApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'managed': False},
        ),
    ]
